apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: keep2todoist
  name: keep2todoist
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keep2todoist
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/kubernetes-default: "true"
        io.kompose.service: keep2todoist
    spec:
      containers:
        - env:
            - name: access_id
              valueFrom:
                secretKeyRef:
                  key: access_id
                  name: akeyless-cred
            - name: access_key
              valueFrom:
                secretKeyRef:
                  key: access_key
                  name: akeyless-cred
          image: ghcr.io/viertel97/keep2todoist:main
          name: keep2todoist
          pullPolicy: Always
          resources: {}
          volumeMounts:
          - name: config-volume
            mountPath: /app/data
      volumes:
      - name: config-volume
        configMap:
          name: keep2todoist-categories
          items:
          - key: categories.json
            path: categories.json
      restartPolicy: Always      
status: {}
